/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PRESENTACION;

import DATOS.Cliente;
import DATOS.Conexion;
import LOGICA.ClienteC;
import LOGICA.ICliente;
import java.awt.Graphics;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.SpinnerNumberModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author 
 */
public class Clientes extends javax.swing.JFrame {
    Conexion cc=new Conexion();
    Connection conectando=cc.getConexion();
    /**
     * Creates new form Cliente
     */
    public Clientes() {
        this.setContentPane(new ImagenFondo());
        initComponents();
        lblimagen.setIcon(CargarImagen(0)); // 0 representa la imagen predeterminada
        SpinnerNumberModel modeloSPI= new SpinnerNumberModel();
        modeloSPI.setMinimum(0);
        modeloSPI.setMaximum(5);
        modeloSPI.setStepSize(1);
        this.spcantidad.setModel(modeloSPI);

    }
    
    ImageIcon CargarImagen(int n) {
   ImageIcon imagen1 = new ImageIcon("src/img/G4.png");
   ImageIcon imagen2 = new ImageIcon("src/img/Iphone13.png");
   ImageIcon imagen3 = new ImageIcon("src/img/samsung.png");               
   ImageIcon imagen4 = new ImageIcon("src/img/pixel.png"); 
   ImageIcon imagen5 = new ImageIcon("src/img/oneplus.png"); 
   ImageIcon imagen6 = new ImageIcon("src/img/xperia.png"); 
   ImageIcon imagen7 = new ImageIcon("src/img/xiaomi.png"); 
   ImageIcon imagen8 = new ImageIcon("src/img/rogphone.png");
   ImageIcon imagen9 = new ImageIcon("src/img/motog.png"); 
   ImageIcon imagen10 = new ImageIcon("src/img/nokia.png");
   ImageIcon imagen11 = new ImageIcon("src/img/redmi.png"); 

      
 
    switch(n) {
    case 0: return imagen1;
    case 1: return imagen2;
    case 2: return imagen3;
    case 3: return imagen4;
    case 4: return imagen5;
    case 5: return imagen6;
    case 6: return imagen7;
    case 7: return imagen8;
    case 8: return imagen9;
    case 9: return imagen10;
    case 10: return imagen11;
    default: return imagen1;       
            }
    }
    
    public void setComboBoxSelectedItem(String item) {
        // 
        if (cbocelular != null) {
            cbocelular.setSelectedItem(item);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtnombre = new javax.swing.JTextField();
        txtapellido = new javax.swing.JTextField();
        txtdireccion = new javax.swing.JTextField();
        txttelefono = new javax.swing.JTextField();
        cbocelular = new javax.swing.JComboBox<>();
        txtcorreo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        lblimagen = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        spcantidad = new javax.swing.JSpinner();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtnombre.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        txtnombre.setBorder(null);
        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });

        txtapellido.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        txtapellido.setBorder(null);

        txtdireccion.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        txtdireccion.setBorder(null);
        txtdireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdireccionActionPerformed(evt);
            }
        });

        txttelefono.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        txttelefono.setBorder(null);
        txttelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelefonoActionPerformed(evt);
            }
        });

        cbocelular.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escoge tu celular", "13 Pro Max", "S21 Ultra", "Pixel 6 Pro", "9 Pro", "Xperia 1 III", "Mi 11 Ultra", "ROG Phone 5", "G Power (2021)", "5.4", "Note 10 Pro" }));
        cbocelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbocelularActionPerformed(evt);
            }
        });

        txtcorreo.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        txtcorreo.setBorder(null);
        txtcorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcorreoActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(12, 192, 223));
        jButton1.setText("COMPRAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(12, 192, 223));
        jButton2.setText("FACTURA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(12, 192, 223));
        jButton3.setText("IMPRIMIR FACTURA");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtapellido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                                    .addComponent(txttelefono, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtdireccion, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtcorreo)))
                            .addComponent(cbocelular, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(spcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))))))
                .addGap(272, 272, 272)
                .addComponent(lblimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(cbocelular, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                            .addComponent(spcantidad))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbocelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbocelularActionPerformed
        // TODO add your handling code here:
            this.lblimagen.setIcon(CargarImagen(this.cbocelular.getSelectedIndex()));
    }//GEN-LAST:event_cbocelularActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
    try {
        // Validar campos requeridos
        if (camposRequeridosVacios()) {
            JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos para generar la compra.");
            return;
        }

        // Validar formato del correo electrónico
        String correo = txtcorreo.getText();
        if (!esFormatoCorreoValido(correo)) {
            JOptionPane.showMessageDialog(null, "Formato de correo electrónico incorrecto.", "Error de Validación", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar restricciones adicionales en campos
        if (contieneNumeros(txtnombre.getText()) || contieneNumeros(txtapellido.getText())) {
            JOptionPane.showMessageDialog(null, "Los campos de nombre y apellido no deben contener números.", "Error de Validación", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Resto del código para la compra
        String nombre = txtnombre.getText();
        String apellido = txtapellido.getText();
        String direccion = txtdireccion.getText();
        int telefono = Integer.parseInt(txttelefono.getText());
        String celular = String.valueOf(cbocelular.getSelectedItem());
        int cantidad = Integer.parseInt(spcantidad.getValue().toString());

        ICliente em = new ClienteC();
        Cliente empleadito = new Cliente();
        empleadito = em.verificaCallableStatement(nombre, apellido, direccion, telefono, correo, celular, cantidad);

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "El valor ingresado en el campo de teléfono no es válido.", "Error de Validación", JOptionPane.ERROR_MESSAGE);
    }


               
        

    }//GEN-LAST:event_jButton1ActionPerformed
    private boolean esFormatoCorreoValido(String correo) {
    String regex = "^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Z|a-z]{2,}$";
    return correo.matches(regex);
    }
    private boolean camposRequeridosVacios() {
    return txtnombre.getText().isEmpty() || txtapellido.getText().isEmpty()
            || txtdireccion.getText().isEmpty() || txttelefono.getText().isEmpty()
            || txtcorreo.getText().isEmpty() || cbocelular.getSelectedIndex() == -1
            || Integer.parseInt(spcantidad.getValue().toString()) == 0;
    }
    // Método para verificar si una cadena contiene números
    private boolean contieneNumeros(String cadena) {
        return cadena.matches(".*\\d.*");
    }


    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void txtdireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdireccionActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String nombre = txtnombre.getText();
        String apellido = txtapellido.getText();
        String direccion = txtdireccion.getText();
        String telefono = txttelefono.getText();
        String correo = txtcorreo.getText();
        String celular = String.valueOf(cbocelular.getSelectedItem());
        String cantidad2=spcantidad.getValue().toString();
        
        

        // Verificar que todos los campos estén completos
        if (txtnombre.getText().isEmpty() || txtapellido.getText().isEmpty() || 
                    txtdireccion.getText().isEmpty() ||
                    txttelefono.getText().isEmpty()||
                    txtcorreo.getText().isEmpty() ||cbocelular.getSelectedIndex()==-1 
                    || Integer.parseInt(spcantidad.getValue().toString()) == 0)
        {
            JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos antes de generar la factura.");
        } else {
            // Obtener la fecha actual
            LocalDate fechaActual = LocalDate.now();

            // Formatear la fecha en el formato deseado (por ejemplo, "dd/MM/yyyy")
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            String fechaFormateada = fechaActual.format(formatter);
            //int cantidad2;
            
            //cantidad2 = Integer.parseInt(spcantidad.getValue().toString());
            String factura = "FACTURA\n" +
                     "NOMBRE: " + nombre + "\n" +
                     "FECHA DE PEDIDO: " + fechaFormateada + "\n" +
                     "ENVIO: "+"UNA SEMANA APROXIMADAMENTE"+"\n" +
                     "APELLIDO: " + apellido + "\n" +
                     "DIRECCIÓN: " + direccion + "\n" +
                     "TELÉFONO: " + telefono + "\n" +
                     "CORREO: " + correo + "\n" +
                     "CELULAR: " + celular + "\n" +
                     "CANTIDAD: " + cantidad2;

            // Mostrar la factura en un JOptionPane
            JOptionPane.showMessageDialog(null, factura, "Factura", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        String reporte = "\\FacturaCliente.jrxml";
       
        // Verificar que todos los campos estén completos
        if (txtnombre.getText().isEmpty() || txtapellido.getText().isEmpty() || 
                    txtdireccion.getText().isEmpty() ||
                    txttelefono.getText().isEmpty()||
                    txtcorreo.getText().isEmpty() ||cbocelular.getSelectedIndex()==-1 
                    || Integer.parseInt(spcantidad.getValue().toString()) == 0)
        /* txtcantidad.getText().isEmpty()*/ {
            JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos y realice la compra.");
        } else{
        
        try (Connection conectando = cc.getConexion()) {
        // Compilar el archivo de diseño JasperReport
        JasperReport jr = JasperCompileManager.compileReport(reporte);

        // Llenar el informe con datos (puedes proporcionar parámetros si es necesario)
        JasperPrint jp = JasperFillManager.fillReport(jr, null, conectando);

        // Mostrar el informe en un visor
        JasperViewer.viewReport(jp, false);
    } catch (SQLException | JRException ex) {
        JOptionPane.showMessageDialog(null, ex.toString());
    }
        }
        Limpiar();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txttelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelefonoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txttelefonoActionPerformed

    private void txtcorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcorreoActionPerformed
    
    public void Limpiar(){
        txtnombre.setText("");
        txtapellido.setText("");
        txtdireccion.setText("");
        txttelefono.setText("");
        txtcorreo.setText("");
        cbocelular.setSelectedItem(null);
        spcantidad.setValue(0);
        

        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clientes().setVisible(true);
            }
        });
    }
    public class ImagenFondo extends JPanel{
        @Override
        public void paint(Graphics g){
            ImageIcon imagen=new ImageIcon(getClass().getResource("/IMG/clientes.png"));
            g.drawImage(imagen.getImage(),0,0,getWidth(),getHeight(),this);
            setOpaque(false);
            super.paint(g);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbocelular;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel lblimagen;
    private javax.swing.JSpinner spcantidad;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
